version: "3.8"

services:
  calibre:
    container_name: calibre
    image: linuxserver/calibre:latest
    ports:
      - "8081:8081"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/Downloads/books:/data/CalibreLibrary
    restart: on-failure
