version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: beamilkyway-calibre_web_1
      APP_PORT: 8081
    restart: on-failure
  web:
    image: linuxserver/calibre:latest
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "8081:8081"
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${UMBREL_ROOT}/data/Downloads/books:/Calibre Library
    restart: on-failure
