ilkversion: "3.8"

services:
  app_proxy:
    environment:
      APP_HOST: beamilkyway-calibre_web_1
      APP_PORT: 8081
    restart: on-failure

  calibre:
    image: linuxserver/calibre:latest
    container_name: calibre
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "America/Sao_Paulo"
    ports:
      - 8081:8081
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${UMBREL_ROOT}/data/Downloads/books:/data/Calibre Library
    restart: on-failure
