version: "3.8"

services:

  calibre:
    container-name: calibre
    image: linuxserver/calibre:latest
    ports:
      - "8081:8081"
    env:
      PUID: 1000
      PGID: 1000
      TZ: "America/Sao_Paulo"
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/Downloads/books:/data/Calibre Library

    restart: on-failure
