version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: beamilkyway-kavita-reader_web_1
      APP_PORT: 5001
  web:
    image: kizaing/kavita:latest
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "5001:5000"
    volumes:
      - ${UMBREL_ROOT}/home/Downloads/books:/books
      - ${APP_DATA_DIR}:/kavita/config


