version: "3.8"

services:

  kavita:
    container-name: kavita
    image: kizaing/kavita:latest
    ports:
      - "5001:5001"
    env:
      PUID: 1000
      PGID: 1000
      TZ: "America/Sao_Paulo"
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/Downloads/books:/data/books

    restart: on-failure


